name: Publish draft release

on: ["push"]
  # push:
  #   tags:
  #     - v**.**.**

jobs:
  build-runtimes:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Submodules
      run: git submodule update --init --recursive
    - name: Cache Rust dependencies
      uses: actions/cache@v1.1.2
      with:
        path: target
        key: ${{ runner.OS }}-build-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.OS }}-build-
    - uses: actions-rs/toolchain@v1
      with:
        target: wasm32-unknown-unknown
        toolchain: nightly
        default: true
    - name: Build
      run: cargo build --release --verbose --all
    - name: Upload moonbeam runtime
      uses: actions/upload-artifact@v2
      with:
        name: moonbeam-runtime
        path: "target/release/wbuild/moonbeam-runtime/moonbeam_runtime.compact.wasm"
    - name: Upload moonbeam node
      uses: actions/upload-artifact@v2
      with:
        name: moonbeam
        path: "target/release/node-moonbeam"

  get-rust-versions:
    runs-on: self-hosted
    container:
      image: paritytech/ci-linux:production
    outputs:
      rustc-stable: ${{ steps.get-rust-versions.outputs.stable }}
      rustc-nightly: ${{ steps.get-rust-versions.outputs.nightly }}
    steps:
      - id: get-rust-versions
        run: |
          echo "::set-output name=stable::$(rustc +stable --version)"
          echo "::set-output name=nightly::$(rustc +nightly --version)"

  publish-draft-release:
    runs-on: self-hosted
    needs: ['get-rust-versions', 'build-runtimes']
    outputs:
      release_url: ${{ steps.create-release.outputs.html_url }}
      asset_upload_url: ${{ steps.create-release.outputs.upload_url }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        path: moonbeam
    - name: Download srtool json output
      uses: actions/download-artifact@v2
    - name: Generate release text
      env:
        RUSTC_STABLE: ${{ needs.get-rust-versions.outputs.rustc-stable }}
        RUSTC_NIGHTLY: ${{ needs.get-rust-versions.outputs.rustc-nightly }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # gem install changelogerator git toml
        ruby $GITHUB_WORKSPACE/moonbeam/scripts/github/generate_release_text.rb | tee release_text.md
    - name: Create draft release
      id: create-release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Moonbeam ${{ github.ref }}
        body_path: ./release_text.md
        draft: true

  post_to_matrix:
    runs-on: ubuntu-latest
    needs: publish-draft-release
    steps:
      - name: Internal moonbeam channel
        uses: s3krit/matrix-message-action@v0.0.2
        with:
          room_id: ${{ secrets.INTERNAL_MOONBEAM_MATRIX_ROOM_ID }}
          access_token: ${{ secrets.MATRIX_ACCESS_TOKEN }}
          message: "**New version of moonbeam tagged**: ${{ github.ref }}<br/>Alan: Draft release created: ${{ needs.publish-draft-release.outputs.release_url }}"
          server: "matrix-client.matrix.org"

  publish-runtimes:
    runs-on: ubuntu-latest
    needs: ['publish-draft-release']
    strategy:
      matrix:
        runtime: ['moonbeam']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.runtime }}-runtime
      - uses: actions/download-artifact@v2
        with:
          name: ${{ matrix.runtime }}
      - name: Set up Ruby 2.7
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Get runtime version
        id: get-runtime-ver
        run: |
          runtime_ver="$(ruby -e 'require "./scripts/github/lib.rb"; puts get_runtime("${{ matrix.runtime }}")')"
          echo "::set-output name=runtime_ver::$runtime_ver"
      - name: Upload ${{ matrix.runtime }} wasm
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-draft-release.outputs.asset_upload_url }}
          asset_path: ./${{ matrix.runtime }}_runtime.compact.wasm
          asset_name: ${{ matrix.runtime }}_runtime-v${{ steps.get-runtime-ver.outputs.runtime_ver }}.compact.wasm
          asset_content_type: application/wasm
      - name: Upload ${{ matrix.runtime }} node
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.publish-draft-release.outputs.asset_upload_url }}
          asset_path: ./node-${{ matrix.runtime }}
          asset_name: ${{ matrix.runtime }}
          asset_content_type: application/octet-stream